### ISSUE TITLE
Unusual definition of `distributeM`

### ISSUE THREAD

**Issue by clintonmead** [blamario/grampa#4]
I've noticed that the definition of `distributeM` in the package is strange, as it doesn't seem to be the equivalent of [distributeM](https://hackage.haskell.org/package/distributive-0.5.2/docs/Data-Distributive.html#v:distributeM) in the [distributive](https://hackage.haskell.org/package/distributive-0.5.2) package.

`distributeM` currently has this signature:

`(Distributive g, Rank1.Monad f) => f (g f) -> g f`

But I believe it should have this signature:

`(Distributive g, Monad m) => m (g p) -> g (Compose m p)`

That is, the dual of `sequence`.

Perhaps `distributeM` should be renamed should be renamed to `join`? (Is it the rank to equivalent of join?!). And a new `distributeM` created which follows the suggested signature.

**Comment by blamario** [comment]
The `distributeM` function from the `distributive` package has no reason to exist since AMP.  It should eventually be put out of its misery, together with the monadic `sequence` function. I don't want to replicate this historic baggage in a fresh context where there's no backward-compatibility pressure.

Perhaps I should have picked a different name for `Rank2.distributeM` to avoid confusion? I don't like `join`, but I'm open to alternative suggestions.  Would you prefer `distributeJoin`?

**Comment by blamario** [comment]
After some consideration, I went ahead and renamed `distributeM` to `distributeJoin`.
